<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'maker.doctrine_entity_helper' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/maker-bundle/src/Doctrine/DoctrineEntityHelper.php';

return $this->services['maker.doctrine_entity_helper'] = new \Symfony\Bundle\MakerBundle\Doctrine\DoctrineEntityHelper(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
