<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWkn0bqr\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWkn0bqr/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWkn0bqr.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWkn0bqr\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWkn0bqr\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Wkn0bqr',
    'container.build_id' => '5e056808',
    'container.build_time' => 1522003912,
));
