<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFjhzkwu\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFjhzkwu/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFjhzkwu.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFjhzkwu\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFjhzkwu\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Fjhzkwu',
    'container.build_id' => 'c3986ea2',
    'container.build_time' => 1522054668,
));
