<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX3kpxgp\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX3kpxgp/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX3kpxgp.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX3kpxgp\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerX3kpxgp\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'X3kpxgp',
    'container.build_id' => '2e2d38cd',
    'container.build_time' => 1521710056,
));
